name: Generate Propeller Profile from Existing Data

on:
  workflow_dispatch:
    inputs:
      VMLINUX_PATH:
        description: "vmlinux 文件路径（对应于您的 kernel.afdo）"
        required: true
        default: "https://github.com/3620603660/afdo.git"
      PERF_DATA_PATH:
        description: "perf.data 文件路径"
        required: true
        default: "https://github.com/3620603660/perf.git"
      PROPELLER_PROFILE_PREFIX:
        description: "Propeller 配置文件前缀"
        required: true
        default: "propeller_profile"



jobs:
  generate_profile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup LLVM and Clang (Requires LLVM 19+)
        run: |
          # 更新 apt 缓存并安装 clang-19 和 lld-19
          sudo apt-get update
          sudo apt-get install -y clang-19 lld-19
          # 将 LLVM 19 的 bin 目录添加到 PATH，并设置 CC/CXX 环境变量
          echo "PATH=/usr/lib/llvm-19/bin:$PATH" >> $GITHUB_ENV
          echo "CC=clang-19" >> $GITHUB_ENV
          echo "CXX=clang++-19" >> $GITHUB_ENV

      - name: Install Build Dependencies (Protobuf, libelf) # 新增步骤，安装 autofdo 所需的依赖
        run: |
          sudo apt-get update
          sudo apt-get install -y libprotobuf-dev protobuf-compiler libelf-dev

      - name: Install AutoFDO tools (create_llvm_prof)
        run: |
          # 克隆 AutoFDO 官方仓库
          git clone https://github.com/google/autofdo.git autofdo_custom
          cd autofdo_custom
          # 初始化并更新 Git 子模块，确保 LLVM 源代码正确拉取
          git submodule update --init --recursive
          
          mkdir build && cd build
          # 使用 Release 构建类型配置 CMake
          cmake .. -DCMAKE_BUILD_TYPE=Release
          make -j$(nproc)
          # 将构建目录添加到 PATH 环境变量，以便后续步骤可以找到 create_llvm_prof
          echo "PATH=$GITHUB_WORKSPACE/autofdo_custom/build:$PATH" >> $GITHUB_ENV

      - name: Prepare vmlinux and perf.data
        run: |
          # 检查 vmlinux 和 perf.data 文件是否存在于指定路径
          # 注意：如果这些文件是通过 artifact 上传的，您需要在前面添加 actions/download-artifact 步骤
          
          # 示例：如果您的 vmlinux 和 perf.data 是通过 actions/upload-artifact 上传的，
          # 您需要在这里使用 actions/download-artifact 来下载它们。
          # 假设它们被下载到当前工作目录（即 .）
          
          # - name: Download vmlinux artifact # 如果需要下载，请取消注释
          #   uses: actions/download-artifact@v4
          #   with:
          #     name: vmlinux-artifact # 替换为实际的 artifact 名称
          #     path: . # 下载到当前目录，这样 ${{ github.event.inputs.VMLINUX_PATH }} 就可以是 ./vmlinux

          # - name: Download perf.data artifact # 如果需要下载，请取消注释
          #   uses: actions/download-artifact@v4
          #   with:
          #     name: perf-data-artifact # 替换为实际的 artifact 名称
          #     path: . # 下载到当前目录，这样 ${{ github.event.inputs.PERF_DATA_PATH }} 就可以是 ./perf.data

          # 确保 vmlinux 和 perf.data 文件存在于指定路径
          if [ ! -f "${{ github.event.inputs.VMLINUX_PATH }}" ]; then
            echo "Error: vmlinux file not found at ${{ github.event.inputs.VMLINUX_PATH }}"
            exit 1
          fi
          if [ ! -f "${{ github.event.inputs.PERF_DATA_PATH }}" ]; then
            echo "Error: perf.data file not found at ${{ github.event.inputs.PERF_DATA_PATH }}"
            exit 1
          fi
          echo "vmlinux and perf.data are ready."

      - name: Generate Propeller Profiles
        run: |
          # 确保 create_llvm_prof 在 PATH 中可用
          # 确保 vmlinux 文件是完整的，并且 perf.data 包含有效的性能数据。
          # create_llvm_prof 的具体参数可能需要根据您的 perf 数据和内核版本进行调整。
          create_llvm_prof \
            --binary=${{ github.event.inputs.VMLINUX_PATH }} \
            --profile=${{ github.event.inputs.PERF_DATA_PATH }} \
            --format=propeller \
            --propeller_output_module_name \
            --out=${{ github.event.inputs.PROPELLER_PROFILE_PREFIX }}_cc_profile.txt \
            --propeller_symorder=${{ github.event.inputs.PROPELLER_PROFILE_PREFIX }}_ld_profile.txt
          echo "✅ Propeller 配置文件生成完成"

      - name: Upload Propeller Profiles
        uses: actions/upload-artifact@v4
        with:
          name: propeller-profiles
          path: |
            ${{ github.event.inputs.PROPELLER_PROFILE_PREFIX }}_cc_profile.txt
            ${{ github.event.inputs.PROPELLER_PROFILE_PREFIX }}_ld_profile.txt